name: SCC CI

on:
  push:
    branches: [ "main" ]
    
permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Automated Testing
      shell: bash
      run: |
          ant -noinput -buildfile build.xml testall
    - name: Archive JUnit Test Reports
      uses: actions/upload-artifact@v3
      with:
          name: junit-reports
          path: '**/build/report/index.html'
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
          report_paths: '**/home/runner/work/freecol/freecol/build/report/index.html'
          
