name: SCC CI test

on:
  push:
    branches: [ "main" ]
    
permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Install Ant
      run: sudo apt-get install ant  # Install Ant on the runner

    - name: Build with Ant
      run: ant  
  test: 
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - name: Automated Testing
       shell: bash
       run: |
          ant -noinput -buildfile build.xml testall
          
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          - java -Xmx4000M -jar FreeCol.jar  # Deploy your application
